#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 14 00:43:03 EEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim circle_tb_behav -key {Behavioral:sim_1:Functional:circle_tb} -tclbatch circle_tb.tcl -view /home/palade/circle_bresenham/circle_tb_behav.wcfg -log simulate.log"
xsim circle_tb_behav -key {Behavioral:sim_1:Functional:circle_tb} -tclbatch circle_tb.tcl -view /home/palade/circle_bresenham/circle_tb_behav.wcfg -log simulate.log

